import { useCallback, useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Alert, Button, Card, CardBody, Chip } from '@heroui/react'
import { BackButton, EmptyState, LoadingPage, PageShell } from './PageShell'

interface SummaryData {
  id: string
  kind: string
  shortSummary: string | null
  detailedSummary: string | null
  keyPoints: string[]
  decisions: string[]
  risks: string[]
  openQuestions: string[]
  actionItems: Array<{ title: string; description: string; priority?: string; confidence: number }>
  modelName: string
  createdAt: string
}

export function SummaryPage() {
  const { id } = useParams<{ id: string }>()
  const [summary, setSummary] = useState<SummaryData | null>(null)
  const [loading, setLoading] = useState(true)

  const loadSummary = useCallback(async () => {
    if (!id) return
    setLoading(true)
    try {
      const res = await fetch(`/api/media/${id}/summary`)
      if (res.ok) setSummary(await res.json())
    } catch {}
    setLoading(false)
  }, [id])

  useEffect(() => { loadSummary() }, [loadSummary])

  const handleExport = (format: 'md' | 'json') => {
    if (id) window.open(`/api/media/${id}/export/summary.${format}`, '_blank')
  }

  if (loading) return <LoadingPage label="Summary" />

  if (!summary) {
    return (
      <PageShell title="Summary" subtitle="No summary available yet" eyebrow="Media" actions={<BackButton />} width="lg">
        <EmptyState title="No summary" description="Process the media file first to generate a summary." />
      </PageShell>
    )
  }

  return (
    <PageShell
      title="Summary"
      subtitle={`Generated by ${summary.modelName} · ${new Date(summary.createdAt).toLocaleString()}`}
      eyebrow="Media"
      actions={
        <div className="flex gap-2">
          <Button size="sm" variant="flat" radius="sm" onPress={() => handleExport('md')}>Export .md</Button>
          <Button size="sm" variant="flat" radius="sm" onPress={() => handleExport('json')}>Export .json</Button>
        </div>
      }
      width="xl"
    >
      {summary.shortSummary && <Alert color="primary" variant="flat" title="Short summary" description={summary.shortSummary} />}

      {summary.detailedSummary && (
        <Section title="Detailed summary">
          <p className="whitespace-pre-wrap text-small leading-7 text-default-600">{summary.detailedSummary}</p>
        </Section>
      )}

      <div className="grid grid-cols-2 gap-4">
        <ListSection title="Key points" items={summary.keyPoints} color="primary" />
        <ListSection title="Decisions" items={summary.decisions} color="success" />
        <ListSection title="Risks" items={summary.risks} color="warning" />
        <ListSection title="Open questions" items={summary.openQuestions} color="secondary" />
      </div>

      {summary.actionItems?.length > 0 && (
        <Section title="Action items">
          <div className="grid gap-3">
            {summary.actionItems.map((item, index) => (
              <Card key={`${item.title}-${index}`} radius="sm" className="border border-default-100 bg-content1">
                <CardBody className="gap-2 p-4">
                  <div className="flex items-center justify-between gap-3">
                    <p className="font-semibold">{item.title}</p>
                    {item.priority && <Chip size="sm" color={priorityColor(item.priority)} variant="flat" radius="sm">{item.priority}</Chip>}
                  </div>
                  <p className="text-small text-default-500">{item.description}</p>
                  <Chip size="sm" variant="flat" radius="sm">confidence {(item.confidence * 100).toFixed(0)}%</Chip>
                </CardBody>
              </Card>
            ))}
          </div>
          <Button color="primary" variant="flat" radius="sm" onPress={() => (window.location.href = `/media/${id}/tasks`)}>
            View tasks
          </Button>
        </Section>
      )}

      <BackButton />
    </PageShell>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Card radius="sm" className="border border-default-100 bg-content2">
      <CardBody className="gap-4 p-5">
        <h2 className="font-semibold">{title}</h2>
        {children}
      </CardBody>
    </Card>
  )
}

function ListSection({ title, items, color }: { title: string; items?: string[]; color: 'primary' | 'success' | 'warning' | 'secondary' }) {
  return (
    <Card radius="sm" className="border border-default-100 bg-content2">
      <CardBody className="gap-3 p-5">
        <div className="flex items-center justify-between">
          <h2 className="font-semibold">{title}</h2>
          <Chip size="sm" color={color} variant="flat" radius="sm">{items?.length ?? 0}</Chip>
        </div>
        {items?.length ? (
          <div className="grid gap-2">
            {items.map((item, index) => <p key={`${item}-${index}`} className="rounded-small bg-content1 p-3 text-small text-default-600">{item}</p>)}
          </div>
        ) : (
          <p className="text-small text-default-500">No items.</p>
        )}
      </CardBody>
    </Card>
  )
}

function priorityColor(priority: string): 'default' | 'warning' | 'danger' {
  if (priority === 'high') return 'danger'
  if (priority === 'medium') return 'warning'
  return 'default'
}
